version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      - db

  db:
    image: postgres:14.2
    ports:
      - ${DATABASE_PORT}:5432
    container_name: schedule-task-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=starwars
      - POSTGRES_DB=scheduleTask
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
